-- SQLite Database Schema for Othello Game
-- Converted from MySQL

CREATE TABLE IF NOT EXISTS games (
  id TEXT PRIMARY KEY,
  w TEXT,
  b TEXT,
  turnCount INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS squares (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id TEXT NOT NULL,
  x INTEGER NOT NULL,
  y INTEGER NOT NULL,
  value TEXT,
  UNIQUE(game_id, x, y),
  FOREIGN KEY(game_id) REFERENCES games(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS bValidMoves (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id TEXT NOT NULL,
  x INTEGER NOT NULL,
  y INTEGER NOT NULL,
  UNIQUE(game_id, x, y),
  FOREIGN KEY(game_id) REFERENCES games(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS wValidMoves (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id TEXT NOT NULL,
  x INTEGER NOT NULL,
  y INTEGER NOT NULL,
  UNIQUE(game_id, x, y),
  FOREIGN KEY(game_id) REFERENCES games(id) ON DELETE CASCADE ON UPDATE CASCADE
);
